config/routes.rb
Rails.application.routes.draw do
  resources :ventures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/venture.rb
class Venture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ventures_controller.rb
class VenturesController < ApplicationController
  before_action :set_venture, only: [:show, :edit, :update, :destroy]

  # GET /ventures
  # GET /ventures.json
  def index
    @ventures = Venture.all
  end

  # GET /ventures/1
  # GET /ventures/1.json
  def show
  end

  # GET /ventures/new
  def new
    @venture = Venture.new
  end

  # GET /ventures/1/edit
  def edit
  end

  # POST /ventures
  # POST /ventures.json
  def create
    @venture = Venture.new(venture_params)

    respond_to do |format|
      if @venture.save
        format.html { redirect_to @venture, notice: 'Venture was successfully created.' }
        format.json { render :show, status: :created, location: @venture }
      else
        format.html { render :new }
        format.json { render json: @venture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventures/1
  # PATCH/PUT /ventures/1.json
  def update
    respond_to do |format|
      if @venture.update(venture_params)
        format.html { redirect_to @venture, notice: 'Venture was successfully updated.' }
        format.json { render :show, status: :ok, location: @venture }
      else
        format.html { render :edit }
        format.json { render json: @venture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventures/1
  # DELETE /ventures/1.json
  def destroy
    @venture.destroy
    respond_to do |format|
      format.html { redirect_to ventures_url, notice: 'Venture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venture
      @venture = Venture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venture_params
      params.require(:venture).permit(:name, :website, :description, :country, :price_range)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ventures_helper.rb
module VenturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethik</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ventures/_form.html.erb
<%= form_for(venture) do |f| %>
  <% if venture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venture.errors.count, "error") %> prohibited this venture from being saved:</h2>

      <ul>
      <% venture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :price_range %>
    <%= f.text_field :price_range %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ventures/edit.html.erb
<h1>Editing Venture</h1>

<%= render 'form', venture: @venture %>

<%= link_to 'Show', @venture %> |
<%= link_to 'Back', ventures_path %>

app/views/ventures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventures</h1>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Description</th>
      <th>Country</th>
      <th>Price range</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ventures.each do |venture| %>
      <tr>
        <td><%= venture.name %></td>
        <td><%= venture.website %></td>
        <td><%= venture.description %></td>
        <td><%= venture.country %></td>
        <td><%= venture.price_range %></td>
        <td><%= link_to 'Show', venture %></td>
        <td><%= link_to 'Edit', edit_venture_path(venture) %></td>
        <td><%= link_to 'Destroy', venture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venture', new_venture_path %>

app/views/ventures/new.html.erb
<h1>New Venture</h1>

<%= render 'form', venture: @venture %>

<%= link_to 'Back', ventures_path %>

app/views/ventures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venture.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @venture.website %>
</p>

<p>
  <strong>Description:</strong>
  <%= @venture.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @venture.country %>
</p>

<p>
  <strong>Price range:</strong>
  <%= @venture.price_range %>
</p>

<%= link_to 'Edit', edit_venture_path(@venture) %> |
<%= link_to 'Back', ventures_path %>